# .github/workflows/cd.yml
name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl
          ini-values: |
            post_max_size=256M
            upload_max_filesize=256M
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: '35135135135135135'
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan your_server_ip >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa user@your_server_ip "cd /path/to/app && git pull origin main && composer install"
