# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          ini-values: |
            post_max_size=256M
            upload_max_filesize=256M
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit
